ENV['VAGRANT_NO_PARALLEL'] = ENV['E2E_STANDUP_PARALLEL'] ? nil : 'no'
NODE_ROLES = (ENV['E2E_NODE_ROLES'] ||
  ["server-0"])
NODE_BOXES = (ENV['E2E_NODE_BOXES'] ||
  ['bento/ubuntu-24.04'])
GITHUB_BRANCH = (ENV['E2E_GITHUB_BRANCH'] || "master")
RELEASE_VERSION = (ENV['E2E_RELEASE_VERSION'] || "")
HARDENED = (ENV['E2E_HARDENED'] || "")
NODE_CPUS = (ENV['E2E_NODE_CPUS'] || 2).to_i
NODE_MEMORY = (ENV['E2E_NODE_MEMORY'] || 3072).to_i
CNI = (ENV['E2E_CNI'] || "canal") # canal, cilium and calico supported
REGISTRY = (ENV['E2E_REGISTRY'] || "")
# Virtualbox >= 6.1.28 require `/etc/vbox/network.conf` for expanded private networks,
# see https://www.virtualbox.org/manual/ch06.html#network_hostonly
NETWORK_PREFIX = "10.10.10"
install_type = ""

def provision(vm, role, role_num, node_num)
 vm.box = NODE_BOXES[node_num]
  vm.hostname = "#{role[0]}-#{role_num}"
  # An expanded netmask is required to allow VM<-->VM communication, virtualbox defaults to /32
  node_ip = "#{NETWORK_PREFIX}.#{100+node_num}"
  vm.network "private_network", ip: node_ip, netmask: "255.255.255.0"

  scripts_location = Dir.exist?("./scripts") ? "./scripts" : "../scripts" 
  vagrant_defaults = File.exist?("./vagrantdefaults.rb") ? "./vagrantdefaults.rb" : "../vagrantdefaults.rb"
  load vagrant_defaults
  
  defaultOSConfigure(vm)

  install_type = getInstallType(vm, RELEASE_VERSION, GITHUB_BRANCH)

  if !HARDENED.empty? 
    cisPrep(vm)
  end

  runS3mock = <<~'SCRIPT'
    docker run -p 9090:9090 -p 9191:9191 -d -e initialBuckets=test-bucket -e debug=true -t mirror.gcr.io/adobe/s3mock
  SCRIPT

  if role.include?("server") && role_num == 0
    dockerInstall(vm)
    vm.provision "run-S3-mock", type: "shell", inline: runS3mock
    vm.provision :rke2, run: 'once' do |rke2|
      rke2.config_mode = '0644'
      rke2.env = %W[INSTALL_RKE2_TYPE=server #{install_type}]
      rke2.config = <<~YAML
        token: vagrant-rke2
        node-external-ip: #{NETWORK_PREFIX}.100
        node-ip: #{NETWORK_PREFIX}.100
        cni: #{CNI}
        etcd-snapshot-schedule-cron: '*/1 * * * *'
        etcd-snapshot-retention: 2
        etcd-s3: true
        etcd-s3-config-secret: rke2-etcd-s3-config
      YAML
    end
  end
end


Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-rke2", "vagrant-reload"]
  # Default provider is libvirt, virtualbox is only provided as a backup
  config.vm.provider "libvirt" do |v|
    v.cpus = NODE_CPUS
    v.memory = NODE_MEMORY
  end
  config.vm.provider "virtualbox" do |v|
    v.cpus = NODE_CPUS
    v.memory = NODE_MEMORY
  end
  
  if NODE_ROLES.kind_of?(String)
    NODE_ROLES = NODE_ROLES.split(" ", -1)
  end
  if NODE_BOXES.kind_of?(String)
    NODE_BOXES = NODE_BOXES.split(" ", -1)
  end

  NODE_ROLES.each_with_index do |name, i|
    config.vm.define name do |node|
      roles = name.split("-", -1)
      role_num = roles.pop.to_i
      provision(node.vm, roles, role_num, i)
    end
  end
end
