version: 2
updates:

  # Maintain dependencies for Docker Images
  - package-ecosystem: "docker"
    directory: "/"
    ignore:
      - dependency-name: "rancher/hardened-build-base"
      - dependency-name: "rancher/hardened-kubernetes"
    schedule:
      interval: "weekly"
    labels:
      - "kind/dependabot"
    reviewers:
      - "rancher/k3s"

  # Maintain dependencies for GitHub Actions
  # Runs on the 12th of each month (right before releases), grouped and ignores patch updates to avoid noise
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 12 * *"
    groups:
      action-deps:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
    labels:
      - "kind/dependabot"
    reviewers:
      - "rancher/k3s"
