---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.5.0
  commands:
  - dapper -f Dockerfile --target dapper make dapper-ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: build-image-kubernetes
  image: rancher/build-base:v1.14.2
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - DRONE_TAG=${DRONE_TAG} BUILD_K8S_IMAGE=true make build-image-kubernetes
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    instance:
    - drone-pr.rancher.io

- name: publish-image-kubernetes
  image: rancher/build-base:v1.14.2
  volumes:
    - name: docker
      path: /var/run/docker.sock
  commands:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - DRONE_TAG=${DRONE_TAG} make publish-image-kubernetes
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: publish-image-runtime
  image: rancher/build-base:v1.14.2
  volumes:
    - name: docker
      path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - DRONE_TAG=${DRONE_TAG} make publish-image-runtime
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest-runtime
  image: rancher/build-base:v1.14.2
  volumes:
    - name: docker
      path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - DRONE_TAG=${DRONE_TAG} make publish-manifest-runtime
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
- name: manifest-kubernetes
  image: rancher/build-base:v1.14.2
  volumes:
  - name: docker
    path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - DRONE_TAG=${DRONE_TAG} make publish-manifest-kubernetes
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

depends_on:
- amd64

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: dispatch

platform:
  os: linux
  arch: amd64

steps:
  - name: dispatch
    image: rancher/dapper:v0.5.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      PAT_USERNAME:
        from_secret: pat_username
      PAT_TOKEN:
        from_secret: github_token
    commands:
      - dapper -f Dockerfile --target dapper make dispatch
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

depends_on:
  - manifest

