FROM squidfunk/mkdocs-material
LABEL org.opencontainers.image.url="https://hub.docker.com/r/rancher/rke2-runtime"
LABEL org.opencontainers.image.source="https://github.com/rancher/rke2"
RUN pip install mkdocs-markdownextradata-plugin
RUN apk add -U git openssh

