# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['TEST_INSTALL_PS1'] ||= '../../../install.ps1'

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-reload"]
  config.vm.box = "jborean93/WindowsServer2019"
  config.vm.boot_timeout = ENV['TEST_VM_BOOT_TIMEOUT'] || 600 # seconds
  config.vm.synced_folder '.', '/vagrant', disabled: true
  %w[libvirt virtualbox hyperv].each do |p|
    config.vm.provider p do |v, o|
      v.cpus = ENV['TEST_VM_CPUS'] || 2
      v.memory = ENV['TEST_VM_MEMORY'] || 3072
    end
  end

  config.vm.define "install-windows-2019", primary: true do |test|
    test.vm.hostname = 'smoke'
    test.vm.provision :shell, privileged: true, run: "once", inline: "Install-WindowsFeature -Name Containers"
    test.vm.provision :reload
    test.vm.provision 'rke2-upload-installer', type: 'file', run: 'always', source: ENV['TEST_INSTALL_PS1'], destination: 'install.ps1'
    test.vm.provision "rke2-install", type: "shell",  privileged: true, run: "once" do |sh|
      sh.env = ENV.select{|k,v| k.start_with?('RKE2_') || k.start_with?('INSTALL_RKE2_')}.merge({
        :INSTALL_RKE2_TYPE => 'AGENT'
      })
      sh.inline = <<~SHELL
        Write-Host "Installing RKE2 as an agent..."
        Push-Location C:\\Users\\vagrant\\Documents
        ./install.ps1

        Write-Host "Adding RKE2 Windows Service..."
        $env:PATH+=";C:\\usr\\local\\bin;C:\\var\\lib\\rancher\\rke2\\bin"
        Push-Location c:\\usr\\local\\bin
        rke2.exe agent service --add
        Pop-Location
        Start-Sleep -s 5

        if(Get-Service rke2 -ErrorAction Ignore) {
            exit 0
        }
        else {
            exit 1
        }
      SHELL
    end
  end
end
