ENV['TEST_INSTALL_SH'] ||= '../../../install.sh'
ENV['VAGRANT_NO_PARALLEL'] = ENV['E2E_STANDUP_PARALLEL'] ? nil : 'no'
NODE_ROLES = (ENV['E2E_NODE_ROLES'] ||
  ["lb-0", "server-0", "server-1", "server-2", "agent-0"])
NODE_BOXES = (ENV['E2E_NODE_BOXES'] ||
  ['bento/ubuntu-24.04', 'bento/ubuntu-24.04', 'bento/ubuntu-24.04', 'bento/ubuntu-24.04', 'bento/ubuntu-24.04'])
GITHUB_BRANCH = (ENV['E2E_GITHUB_BRANCH'] || "master")
RELEASE_VERSION = (ENV['E2E_RELEASE_VERSION'] || "")
NODE_CPUS = (ENV['E2E_NODE_CPUS'] || 2).to_i
NODE_MEMORY = (ENV['E2E_NODE_MEMORY'] || 3072).to_i
LB_MEMORY = (ENV['E2E_LB_MEMORY'] || 1024).to_i
NETWORK4_PREFIX = "10.10.10"
# Virtual IP fronted by the external load balancer (HAProxy + Keepalived).
# It must not collide with any node's primary IP, so nodes start at .101.
VIP = "#{NETWORK4_PREFIX}.100"
CNI = (ENV['E2E_CNI'] || "canal")
DATAPLANE = (ENV['E2E_DATAPLANE'] || "iptables")
LB_INTERFACE = "eth1"

def node_ip4(node_num)
  "#{NETWORK4_PREFIX}.#{101 + node_num}"
end

# Compute the IPs of all server nodes from their position in NODE_ROLES, so the load
# balancer can be configured with the correct backends.
def server_ips(roles)
  ips = []
  roles.each_with_index do |name, i|
    ips << node_ip4(i) if name.split("-", -1)[0] == "server"
  end
  ips
end

def defaultOSConfigure(vm)
  box = vm.box.to_s
  if box.include?("ubuntu")
    vm.provision "netplan dns", type: "shell", inline: "netplan set ethernets.eth0.nameservers.addresses=[8.8.8.8,1.1.1.1]; netplan apply", run: 'once'
    vm.provision "Install jq", type: "shell", inline: "apt-get install -y jq", run: 'once'
  elsif box.include?("Leap") || box.include?("Tumbleweed")
    vm.provision "Install jq", type: "shell", inline: "zypper install -y jq", run: 'once'
  end
end

def provision(vm, roles, role_num, node_num, all_roles)
  vm.box = NODE_BOXES[node_num]
  vm.hostname = "#{roles[0]}-#{role_num}"
  node_ip = node_ip4(node_num)
  vm.network "private_network",
    :ip => node_ip,
    :netmask => "255.255.255.0",
    :libvirt__dhcp_enabled => false,
    :libvirt__forward_mode => "none"

  defaultOSConfigure(vm)

  scripts_location = Dir.exist?("./scripts") ? "./scripts" : "../scripts"
  vm.provision "Configure second interface", type: "shell", path: scripts_location + "/configure_second_interface.sh", args: [ node_ip, "", "", vm.box ]

  external_env = ""
  ENV.select{|k,v| k.start_with?('RKE2_') || k.start_with?('INSTALL_RKE2_')}.each {|key,value| external_env << "#{key.to_s}=#{value.to_s}"}

  if roles.include?("lb")
    vm.provision "Setup load balancer", type: "shell", path: scripts_location + "/loadbalancer_setup.sh", args: [ VIP, LB_INTERFACE ] + server_ips(all_roles)
    return
  end

  # Server nodes need the CNI HelmChartConfig manifest.
  if roles.include?("server")
    if DATAPLANE == "ebpf"
      vm.provision "Create Calico eBPF Manifest", type: "shell", path: scripts_location + "/calico_ebpf_manifest.sh", args: [ VIP, "6443" ]
    else
      vm.provision "Create CNI Manifest", type: "shell", path: scripts_location + "/create_cni_manifest.sh", args: [ CNI, "iptables" ]
    end
  end

  vm.provision 'rke2-upload-installer', type: 'file', run: 'always', source: ENV['TEST_INSTALL_SH'], destination: 'install.sh'

  if roles.include?("server") && role_num == 0
    vm.provision :rke2, run: 'once' do |rke2|
      rke2.installer_url = 'file:///home/vagrant/install.sh'
      rke2.env = %W[ #{external_env} INSTALL_RKE2_TYPE=server]
      rke2.config_mode = '0644' # side-step https://github.com/k3s-io/k3s/issues/4321
      rke2.config = <<~YAML
        write-kubeconfig-mode: '0644'
        node-external-ip: #{node_ip}
        node-ip: #{node_ip}
        token: vagrant-rke2
        tls-san:
          - #{VIP}
        cni: #{CNI}
        #{DATAPLANE == "ebpf" ? "disable-kube-proxy: true" : ""}
      YAML
    end
  elsif roles.include?("server") && role_num != 0
    vm.provision :rke2, run: 'once' do |rke2|
      rke2.installer_url = 'file:///home/vagrant/install.sh'
      rke2.env = %W[ #{external_env} INSTALL_RKE2_TYPE=server]
      rke2.config_mode = '0644' # side-step https://github.com/k3s-io/k3s/issues/4321
      rke2.config = <<~YAML
        write-kubeconfig-mode: '0644'
        node-external-ip: #{node_ip}
        node-ip: #{node_ip}
        server: https://#{VIP}:9345
        token: vagrant-rke2
        tls-san:
          - #{VIP}
        cni: #{CNI}
        #{DATAPLANE == "ebpf" ? "disable-kube-proxy: true" : ""}
      YAML
    end
  end
  if roles.include?("agent")
    vm.provision :rke2, run: 'once' do |rke2|
      rke2.installer_url = 'file:///home/vagrant/install.sh'
      rke2.env = %W[ #{external_env} INSTALL_RKE2_TYPE=agent]
      rke2.install_path = false
      rke2.config_mode = '0644' # side-step https://github.com/k3s-io/k3s/issues/4321
      rke2.config = <<~YAML
        write-kubeconfig-mode: '0644'
        server: https://#{VIP}:9345
        node-ip: #{node_ip}
        node-external-ip: #{node_ip}
        token: vagrant-rke2
        #{DATAPLANE == "ebpf" ? "disable-kube-proxy: true" : ""}
      YAML
    end
  end
end

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-rke2", "vagrant-reload", "vagrant-libvirt"]
  config.vm.provider "libvirt" do |v|
    v.cpus = NODE_CPUS
    v.memory = NODE_MEMORY
  end

  if NODE_ROLES.kind_of?(String)
    NODE_ROLES = NODE_ROLES.split(" ", -1)
  end
  if NODE_BOXES.kind_of?(String)
    NODE_BOXES = NODE_BOXES.split(" ", -1)
  end

  NODE_ROLES.each_with_index do |name, i|
    config.vm.define name do |node|
      roles = name.split("-", -1)
      role_num = roles.pop.to_i
      # The load balancer node is lightweight; give it less memory to fit the CI runner.
      if roles.include?("lb")
        node.vm.provider "libvirt" do |v|
          v.memory = LB_MEMORY
        end
      end
      provision(node.vm, roles, role_num, i, NODE_ROLES)
    end
  end
end
