name: 'Setup golang with master only caching'
description: 'A composite action that installs golang, but with a caching strategy that only updates the cache on master branch.'
inputs:
  go-version:
    description: 'Override the version of Go to install.'
    required: false

runs:
  using: 'composite'
  steps:
    # On self-hosted runners, the env.ImageOS variable may not be set correctly, which can cause issues with the cache key.
    # We need to handle this case to ensure the cache key is consistent.
    - name: Set ImageOS
      if: ${{ runner.os == 'Linux' && env.ImageOS == '' }}
      shell: bash
      # Key is ubuntu<MAJOR>, as there is not other linux os in GHA other than Ubuntu
      run: echo "ImageOS=ubuntu$(lsb_release -rs | cut -d. -f1)" >> $GITHUB_ENV

    - uses: actions/setup-go@v5
      if: inputs.go-version == ''
      with:
        go-version-file: 'go.mod'  # Just use whatever version is in the go.mod file
        cache: ${{ github.ref == 'refs/heads/master' }}
    
    - uses: actions/setup-go@v5
      if: inputs.go-version != ''
      with:
        go-version: ${{ inputs.go-version }}
        cache: ${{ github.ref == 'refs/heads/master' }}

    - name: Prepare for go cache
      if: ${{ github.ref != 'refs/heads/master' }}
      shell: bash
      run: |
        echo "GO_CACHE=$(go env GOCACHE)" | tee -a "$GITHUB_ENV"
        echo "GO_MODCACHE=$(go env GOMODCACHE)" | tee -a "$GITHUB_ENV"
        echo "GO_VERSION=$(go env GOVERSION | tr -d 'go')" | tee -a "$GITHUB_ENV"

    # Match the cache key to the setup-go action https://github.com/actions/setup-go/blob/main/src/cache-restore.ts#L34
    - name: Create arch key (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: echo "ARCH_OPT=$(echo ${{ runner.arch }} | tr '[:upper:]' '[:lower:]')-${{ env.ImageOS }}" >> $GITHUB_ENV
    
    - name: Create arch key (non-Linux)
      if: ${{ runner.os != 'Linux' }}
      shell: pwsh
      run: echo "ARCH_OPT=$('${{ runner.arch }}'.ToLower())" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Setup read-only cache
      if: ${{ github.ref != 'refs/heads/master' }}
      uses: actions/cache/restore@v4
      with:
        path: |
          ${{ env.GO_MODCACHE }}
          ${{ env.GO_CACHE }}
        key: setup-go-${{ runner.os }}-${{ env.ARCH_OPT }}-go-${{ env.GO_VERSION }}-${{ hashFiles('go.sum') }}