#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

mkdir -p build/images

docker buildx build \
    --build-arg TAG=${VERSION} \
    --build-arg KUBERNETES_VERSION=${KUBERNETES_VERSION} \
    --build-arg MAJOR=${VERSION_MAJOR} \
    --build-arg MINOR=${VERSION_MINOR} \
    --build-arg BUILDARCH=${GOARCH} \
    --build-arg CACHEBUST="$(date +%s%N)" \
    --tag ${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION} \
    --tag ${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-${GOOS}-${GOARCH} \
    --target runtime \
    --file Dockerfile \
    --output type=image \
    --output type=docker,dest=build/images/${PROG}-images.${PLATFORM}.tar \
    .
zstd -T0 -16 -f --long=25 --no-progress build/images/${PROG}-images.${PLATFORM}.tar

if [ "${GOARCH}" != "s390x" ] && [ "${GOARCH}" != "arm64" ] && [ -z "$SKIP_WINDOWS" ]; then
  docker buildx build \
      --build-arg TAG=${VERSION} \
      --build-arg KUBERNETES_VERSION=${KUBERNETES_VERSION} \
      --build-arg MAJOR=${VERSION_MAJOR} \
      --build-arg MINOR=${VERSION_MINOR} \
      --build-arg CACHEBUST="$(date +%s%N)" \
      --tag ${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-windows-amd64 \
      --target windows-runtime \
      --file Dockerfile.windows \
      --output type=image \
      --output type=oci,dest=build/images/${PROG}-images.windows-amd64.tar \
      --platform 'windows(10.0.17763.7919)/amd64,windows(10.0.20348.4294)/amd64,windows(10.0.26100.4294)/amd64' \
      .
  zstd -T0 -16 -f --long=25 --no-progress build/images/${PROG}-images.windows-amd64.tar
fi
