#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh
mkdir -p build/images

./scripts/build-binary

DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-1} docker image build \
    --build-arg TAG=${VERSION} \
    --build-arg KUBERNETES_VERSION=${KUBERNETES_VERSION} \
    --build-arg MAJOR=${VERSION_MAJOR} \
    --build-arg MINOR=${VERSION_MINOR} \
    --build-arg DAPPER_HOST_ARCH=${GOARCH} \
    --tag ${REPO}/${PROG}-supervisor:${DOCKERIZED_VERSION} \
    --tag ${REPO}/${PROG}-supervisor:${DOCKERIZED_VERSION}-${GOOS}-${GOARCH} \
    --target supervisor \
    --file Dockerfile \
    .
