#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

./scripts/build-image-kubernetes
./scripts/build-image-runtime

xargs -n1 -t docker image pull --quiet << EOF > build/images.txt
    ${REGISTRY}/rancher/hardened-calico:v3.13.3-${IMAGE_BUILD_VERSION}
    ${REGISTRY}/rancher/hardened-coredns:v1.6.9-${IMAGE_BUILD_VERSION}
    ${REGISTRY}/rancher/hardened-etcd:${ETCD_VERSION}-${IMAGE_BUILD_VERSION}
    ${REGISTRY}/rancher/hardened-flannel:v0.13.0-rancher1-${IMAGE_BUILD_VERSION}
    ${REGISTRY}/rancher/hardened-k8s-metrics-server:v0.3.6-${IMAGE_BUILD_VERSION}
    ${REGISTRY}/rancher/hardened-kube-proxy:${KUBERNETES_VERSION}
    ${REGISTRY}/rancher/klipper-helm:v0.4.3-build20210225
    ${REGISTRY}/rancher/pause:${PAUSE_VERSION}
    ${REGISTRY}/rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1
    ${REGISTRY}/rancher/nginx-ingress-controller:nginx-0.30.0-rancher1
EOF
echo "${REGISTRY}/${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}" >> build/images.txt
echo "${REGISTRY}/${REPO}/hardened-kubernetes:${DOCKERIZED_VERSION}" >> build/images.txt
docker image save --output build/images/${PROG}-airgap.tar $(<build/images.txt)

./scripts/build-image-test
