#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh
mkdir -p build

WINDOWS_IMAGES=(${REGISTRY}/${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-windows-amd64 mcr.microsoft.com/oss/kubernetes/pause:3.5-windows-1809-amd64 mcr.microsoft.com/oss/kubernetes/pause:3.5-windows-2004-amd64 mcr.microsoft.com/oss/kubernetes/pause:3.5-windows-20H2-amd64)
for IMAGE in "${WINDOWS_IMAGES[@]}"; do
  echo "${IMAGE}" >> build/windows-images.txt
done
