#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

if [ "${GOARCH}" == "s390x" ] || [ "${GOARCH}" == "arm64" ]; then
    exit 0
fi

docker buildx build \
    --load \
    --cache-from type=gha \
    --cache-to type=gha,ignore-error=true,mode=max \
    --build-arg TAG=${VERSION} \
    --build-arg KUBERNETES_VERSION=${KUBERNETES_VERSION} \
    --build-arg CACHEBUST="$(date +%s%N)" \
    --tag ${REPO}/${PROG}-test:${DOCKERIZED_VERSION} \
    --tag ${REPO}/${PROG}-test:${DOCKERIZED_VERSION}-${GOARCH} \
    --target test \
    .

# fix builder activity timestamp file ownership getting broken when mounted into the dapper container
rm ~/.docker/buildx/activity/*
