#!/bin/bash

set -e -x

cd $(dirname $0)/..

. ./scripts/dev-shell-build.sh

IMAGES_DIR=/var/lib/rancher/rke2/agent/images
docker run --rm --name ${PROG}-dev-shell \
  --hostname ${PROG}-server \
  -ti -e WORKSPACE=${PWD} \
  -p 127.0.0.1:2345:2345 \
  -v ${HOME}:${HOME} \
  -v ${PROG} -w ${PWD} \
  --privileged \
  -v ${PROG}-pkg:/go/pkg \
  -v ${PROG}-cache:/root/.cache/go-build \
  ${PROG}-dev \
    bash -c "mkdir -p ${IMAGES_DIR} && cp build/*.tar dist/artifacts/*.tar ${IMAGES_DIR}/ && bash"
