#!/bin/bash

set -e -x

cd $(dirname $0)/..

IMAGE_REPO=rancher

. ./scripts/version.sh

if [ ! -d build/images ]; then
  ./scripts/image
fi
# build the dev shell image
docker build -t ${PROG}-dev --target shell .
