#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

if [ "${GOARCH}" != "amd64" ]; then
    exit 0
fi

if [ -z "${SKIP_DEV_RPM}" ] && [ -z "${DRONE_TAG}" ]; then
    scripts/package-dev-rpm
    scripts/publish-dev-rpm
fi
