#!/bin/bash

set -ex

cd $(dirname $0)/..

. ./scripts/version.sh

IMAGES_DIR=/var/lib/rancher/rke2/agent/images
docker run --rm --name ${PROG}-dev-shell \
    --hostname ${PROG}-server \
    -ti -e WORKSPACE=${PWD} \
    -p 127.0.0.1:2345:2345 \
    -v ${HOME}:${HOME} \
    -v ${PROG} -w ${PWD} \
    -v ${PWD}/build/images:/var/lib/rancher/rke2/agent/images \
    --privileged \
    -v ${PROG}-pkg:/go/pkg \
    -v ${PROG}-cache:/root/.cache/go-build \
    ${PROG}-dev bash
