#!/bin/bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

docker image save \
  ${REGISTRY}/${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-${GOARCH} | \
  zstd -T0 -16 -f --long=25 --no-progress - -o build/images/${PROG}-runtime.${PLATFORM}.tar.zst

docker image save \
  ${REGISTRY}/${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-windows-${ARCH} | \
  zstd -T0 -16 -f --long=25 --no-progress - -o build/images/${PROG}-runtime.windows-${ARCH}.tar.zst

./scripts/build-upload dist/artifacts/${RELEASE}.tar.gz build/images/${PROG}-runtime.${PLATFORM}.tar.zst ${COMMIT}
./scripts/build-upload dist/artifacts/${PROG}.windows-${ARCH}.tar.gz build/images/${PROG}-runtime.windows-${ARCH}.tar.zst ${COMMIT}
