#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

if [ ! -d build/images ]; then
  ./scripts/build-images
fi

# build the dev shell image
docker buildx build --load -t ${PROG}-dev --target shell .
