#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

if [ "${GOARCH}" == "s390x" ]; then
  exit 0
fi

mkdir -p dist/win_artifacts

install -s bin/${PROG}.exe dist/win_artifacts/${PROG}-windows-amd64.exe
