#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

mkdir -p dist/artifacts

# 1809/LTSC
crane --platform windows/amd64 pull \
  ${REGISTRY}/${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-windows-amd64 \
  rancher/pause:3.5-windows-1809-amd64 \
  rke2-windows-1809-amd64-images.tar

# 2004
crane --platform windows/amd64 pull \
  ${REGISTRY}/${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-windows-amd64 \
  rancher/pause:3.5-windows-2004-amd64 \
  rke2-windows-2004-amd64-images.tar

# 20H2
crane --platform windows/amd64 pull \
  ${REGISTRY}/${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-windows-amd64 \
  rancher/pause:3.5-windows-20H2-amd64 \
  rke2-windows-20H2-amd64-images.tar

WINDOWS_TARFILES=(rke2-windows-1809-amd64-images.tar rke2-windows-2004-amd64-images.tar rke2-windows-20H2-amd64-images.tar)
for TARFILE in "${WINDOWS_TARFILES[@]}"; do
    zstd -T0 -16 -f --long=25 --no-progress ${TARFILE} -o dist/artifacts/${TARFILE}.zst
    pigz -v -c ${TARFILE} > dist/artifacts/${TARFILE}.gz
done
cat build/windows-images.txt | sort -V | uniq > dist/artifacts/${PROG}-images.windows-amd64.txt

