#!/bin/bash
set -e -x

cd $(dirname $0)/..

airgap_image_file='scripts/airgap/image-list.txt'
mkdir -p dist/artifacts
cp build/images/airgap.tar dist/artifacts/rke2-airgap-images-amd64.tar
cp "${airgap_image_file}" dist/artifacts/rke2-images.txt
gzip dist/artifacts/rke2-airgap-images-amd64.tar

