#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

if [ "${GOARCH}" == "s390x" ] || [ "${GOARCH}" == "arm64" ]; then
    exit 0
fi

mkdir -p dist/artifacts

install -s bin/${PROG}.exe dist/artifacts/${PROG}-windows-amd64.exe
