#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

docker image push ${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-${GOOS}-${GOARCH}
if [ "${GOARCH}" != "s390x" ]; then
  docker image push ${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-windows-amd64
fi
