#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh
export DOCKER_CLI_EXPERIMENTAL=enabled

docker manifest create \
    --amend ${REPO}/kubernetes:${DOCKERIZED_VERSION} \
    ${REPO}/kubernetes:${DOCKERIZED_VERSION}-${GOARCH}

docker manifest push ${REPO}/kubernetes:${DOCKERIZED_VERSION}
