#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

set +x
docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
set -x

docker image push ${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-${GOOS}-${GOARCH}
if [ "${GOARCH}" != "s390x" ] && [ "${GOARCH}" != "arm64" ]; then
    docker image push ${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-windows-amd64
fi
