#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

GODEBUG=y ./scripts/build-binary
CATTLE_DEV_MODE=true dlv \
  --listen=:2345 \
  --headless=true \
  --api-version=2 \
  --check-go-version=false \
  --accept-multiclient exec -- ./bin/${PROG} ${COMMAND} ${ARGS}
