#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

GODEBUG=y ./scripts/build
go build -o bin/dlv github.com/go-delve/delve/cmd/dlv

CATTLE_DEV_MODE=true ./bin/dlv \
  --listen=:2345 \
  --headless=true \
  --api-version=2 \
  --accept-multigit client exec -- ./bin/${PROG} ${COMMAND} ${ARGS}
