#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

# scan kubernetes image
docker container run --rm \
    --name=scan-rancher-kubernetes \
    --volume /var/run/docker.sock:/var/run/docker.sock \
docker.io/aquasec/trivy:0.10.2 --quiet image \
    --severity ${SEVERITIES="HIGH,CRITICAL"} \
    --no-progress \
    --ignore-unfixed \
    ${REPO}/kubernetes:${DOCKERIZED_VERSION}-${GOARCH}
