#!/usr/bin/env bash
set -ex

source ./scripts/version.sh

BUILDER=${PROG}

docker buildx use ${BUILDER}|| \
    docker buildx create --name=${BUILDER} --platform=linux/amd64,linux/arm64

docker buildx use ${BUILDER}
