#!/bin/bash

calico_services=(
    tigera-operator
    calico-node
)

canal_services=(
    kube-flannel
    calico-node
)

echo "The CNI is $RKE2_CNI"

case $RKE2_CNI in
  calico)
    cni_services=${calico_services[@]}
    ;;
  canal)
    cni_services=${canal_services[@]}
    ;;
esac

echo "The cni_services are ${cni_services[@]}"

all_services=(
    coredns
    etcd
    kube-apiserver
    kube-controller-manager
    kube-proxy
    kube-scheduler
    metrics-server
    ${cni_services[@]}
)

export SERVER_ARGS='--disable=rke2-ingress-nginx --kube-apiserver-arg=kubelet-preferred-address-types=InternalIP'

export NUM_SERVERS=1
export NUM_AGENTS=1
export WAIT_SERVICES="${all_services[@]}"

export sonobuoyParallelArgs=(--e2e-focus='\[Conformance\]' --e2e-skip='\[Serial\]' --e2e-parallel=y)
export sonobuoySerialArgs=(--e2e-focus='\[Serial\].*\[Conformance\]')

start-test() {
  sonobuoy-test $@
}
export -f start-test
