#!/usr/bin/env bash
set -ex

if [ -n "${SKIP_VALIDATE}" ]; then
    echo "skipping validation. continuing..."
    exit 0
fi

if ! command -v golangci-lint; then
    echo Skipping validation: no golangci-lint available
    exit
fi

cd $(dirname $0)/..
GO=${GO-go}

echo Running validation

echo Running: golangci-lint
golangci-lint run -v

echo Running: go fmt
go fmt ./

echo Running: go mod tidy
go mod tidy

. ./scripts/version.sh

if [ -n "$DIRTY" ]; then
    echo Source dir is dirty
    git status --porcelain --untracked-files=no
    exit 1
fi
